name: anima
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shrink_sidemenu: ^1.0.0+3
  google_fonts: ^2.1.0
  cupertino_will_pop_scope: ^1.1.0
  flutter_dotenv: ^5.0.0
  uuid: ^3.0.4
  http: ^0.13.3
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_bloc: ^7.0.1
  lottie: ^1.1.0
  flutter_zoom_drawer: ^2.1.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/langs/
  fonts: 
    - family : Merienda
      fonts: 
        - asset: assets/fonts/Merienda-Bold.ttf
        - asset: assets/fonts/Merienda-Regular.ttf