name: anima
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  flutter_spinkit: ^5.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  equatable: ^2.0.2
  jwt_decoder: ^2.0.1
  http: ^0.13.3
  validators: ^3.0.0
  flutter_translate: ^3.0.1
  flutter_translate_annotations: ^2.0.0
  uuid: ^3.0.4
  rflutter_alert: ^2.0.2
  toggle_switch: ^1.0.0+1 
  font_awesome_flutter: ^9.1.0
  convert: ^3.0.0
  flutter_dotenv: ^5.0.0
  video_player: ^2.1.6
  lottie: ^1.0.1
  google_fonts: ^2.1.0
  shrink_sidemenu: ^1.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - .env
  fonts: 
    - family : Merienda
      fonts: 
        - asset: assets/fonts/Merienda-Bold.ttf
        - asset: assets/fonts/Merienda-Regular.ttf